WARNING: There was an error checking the latest version of pip.
cloning rl-tipping-points
Creating virtual env...
Scoring model...
cloning millie-conservation-agents
Creating virtual env...
Scoring model...
cloning test-rl-leaderboard1
Creating virtual env...
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 2, in <module>
    from stable_baselines3 import A2C, PPO, SAC, DDPG, TD3, DQN, HER
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/stable_baselines3/__init__.py", line 3, in <module>
    from stable_baselines3.a2c import A2C
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/stable_baselines3/a2c/__init__.py", line 1, in <module>
    from stable_baselines3.a2c.a2c import A2C
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py", line 7, in <module>
    from stable_baselines3.common.on_policy_algorithm import OnPolicyAlgorithm
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 8, in <module>
    from stable_baselines3.common.base_class import BaseAlgorithm
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 14, in <module>
    from stable_baselines3.common import utils
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/stable_baselines3/common/utils.py", line 17, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 10, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard1/.virtualenv/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Error with score_model.py for https://github.com/mlap/test-rl-leaderboard1
cloning carl-climate-agents
Creating virtual env...
Scoring model...
cloning rl-leaderboard-output-fishing-v0
Creating virtual env...
Scoring model...
cloning rl-fishing-test
Creating virtual env...
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 2, in <module>
    from stable_baselines3 import A2C, PPO, SAC, DDPG, TD3, DQN, HER
ModuleNotFoundError: No module named 'stable_baselines3'
Error with score_model.py for https://github.com/mchxo/rl-fishing-test
cloning test-rl-leaderboard
Creating virtual env...
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 2, in <module>
    from stable_baselines3 import A2C, PPO, SAC, DDPG, TD3, DQN, HER
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/stable_baselines3/__init__.py", line 3, in <module>
    from stable_baselines3.a2c import A2C
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/stable_baselines3/a2c/__init__.py", line 1, in <module>
    from stable_baselines3.a2c.a2c import A2C
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py", line 7, in <module>
    from stable_baselines3.common.on_policy_algorithm import OnPolicyAlgorithm
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 8, in <module>
    from stable_baselines3.common.base_class import BaseAlgorithm
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 14, in <module>
    from stable_baselines3.common import utils
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/stable_baselines3/common/utils.py", line 17, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 10, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Error with score_model.py for https://github.com/mlap/test-rl-leaderboard
cloning rl-leaderboard-output
Creating virtual env...
Scoring model...
cloning conservation-vanilla
Creating virtual env...
Scoring model...
